# Generated by Django 2.0.1 on 2018-03-26 15:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('settlement_total_fee', models.DecimalField(decimal_places=2, max_digits=25)),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=25)),
                ('trade_type', models.CharField(blank=True, max_length=8, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=32, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=6, null=True)),
                ('out_trade_no', models.CharField(max_length=32)),
                ('time_end', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('startAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('taskName', models.CharField(blank=True, max_length=64, null=True)),
                ('taskContent', models.CharField(blank=True, max_length=512, null=True)),
                ('taskStatus', models.CharField(blank=True, max_length=6, null=True)),
                ('senderNumber', models.CharField(blank=True, max_length=32, null=True)),
                ('receiverNumber', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('version', models.BigIntegerField(blank=True, null=True)),
                ('nickname', models.CharField(blank=True, max_length=128, null=True)),
                ('sex', models.IntegerField(blank=True, default=0, null=True)),
                ('wxlanguage', models.CharField(blank=True, max_length=8, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('province', models.CharField(blank=True, max_length=64, null=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('openid', models.CharField(blank=True, max_length=128, null=True)),
                ('unionid', models.CharField(blank=True, max_length=128, null=True)),
                ('groupid', models.IntegerField(blank=True, null=True)),
                ('subscribe_time', models.DateTimeField(blank=True, null=True)),
                ('subscribe', models.IntegerField(blank=True, default=0, null=True)),
                ('headimgurl', models.URLField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.CharField(blank=True, max_length=32, null=True)),
                ('mobile', models.CharField(max_length=128)),
                ('passwd', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpages.User'),
        ),
    ]
